repos:
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    args: ['-1 79']
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-comprehensions
    - flake8-docstrings
    - flake8-import-order
    - flake8-bugbear